apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  namespace: weather-app
  labels:
    app: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: mohsinrao51/weatherapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  namespace: weather-app
spec:
  type: NodePort
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080

