apiVersion: argoproj.io/v1alpha1 
kind: Application               # Kind of resource
metadata:                        # Metadata section                         
  name: nginx-app         # App name
  namespace: argocd             # Must exist in ArgoCD namespace
spec:
  project: nginx-team        # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/mohsinrao51/weatherapp.git  # Git repo
    targetRevision: main        # Branch to watch
    path: nginx     # Path in repo with manifests
  destination:
    server: https://192.168.194.130:33893 # Target cluster, run `argocd cluster list` to see
    namespace: nginx           # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      # Auto-create namespace if it doesn't exist

