apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-child              # Child app name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohsinrao51/weatherapp.git # Repo containing child apps(that you have forked and cloned earlier)
    targetRevision: main
    path: nginx       # path of Nginx app in `argocd-demos` repo
  destination:
    server: https://192.168.194.130:33893 # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: weather-app           # Deploys into default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
